runtime: python37

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico))$
  static_files: dist/ngEngineersCoreFrontend/\1
  upload: dist/ngEngineersCoreFrontend/(.*)
- url: /(.*)
  static_files: dist/ngEngineersCoreFrontend/index.html
  upload: dist/ngEngineersCoreFrontend/index.html
