runtime: python37
entrypoint: bash -c "python manage.py migrate && gunicorn -b :$PORT engineers_core.wsgi:application"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
