runtime: python37
entrypoint: bash -c "python manage.py migrate && gunicorn -b :$PORT engineers_core.wsgi:application"

env_variables:
  DATABASE_HOST: '/cloudsql/engineers-core:asia-northeast1:engineers-core'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'wbouv2032AUBSce2302'
  EMAIL_HOST_USER: 'sgnmou4f@kke.com'
  EMAIL_HOST_PASSWORD: 'En2019giSg3110Ry'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
