# Generated by Django 2.0.6 on 2019-03-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=1000),
        ),
    ]
