# Generated by Django 2.0.6 on 2019-03-31 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0003_auto_20190331_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_asin', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_count',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='amazonbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.Book'),
        ),
    ]
