# Generated by Django 2.0.6 on 2019-03-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0004_auto_20190331_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='BookStatus',
        ),
    ]
