# Generated by Django 2.0.6 on 2019-03-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0006_auto_20190331_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
