# Generated by Django 2.0.6 on 2019-03-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0007_auto_20190331_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[['PRE', 'Pre-Sales'], ['PUB', 'Published'], ['OOP', 'Out Of Print']], default='PUB', max_length=10),
        ),
    ]
