# Generated by Django 2.0.6 on 2019-03-31 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0008_auto_20190331_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_book', to='engineers_core_api.Book'),
        ),
        migrations.AlterField(
            model_name='amazonbook',
            name='data_asin',
            field=models.BigIntegerField(unique=True),
        ),
    ]
