# Generated by Django 2.0.6 on 2019-03-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0009_auto_20190331_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonbook',
            name='data_asin',
            field=models.CharField(max_length=100),
        ),
    ]
