# Generated by Django 2.0.6 on 2019-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0013_auto_20190331_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonbook',
            name='data_asin',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
