# Generated by Django 2.0.6 on 2019-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0014_auto_20190331_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_link',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
