# Generated by Django 2.0.6 on 2019-04-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0017_bookauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
