# Generated by Django 2.0.6 on 2019-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0018_remove_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
