# Generated by Django 2.0.6 on 2019-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0019_auto_20190402_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='offer_price',
            field=models.IntegerField(null=True),
        ),
    ]
