# Generated by Django 2.0.6 on 2019-04-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0020_book_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=10000)),
                ('comment_date', models.DateField(auto_now=True)),
                ('tweet_flag', models.BooleanField(default=False)),
                ('delete_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_date', models.DateField(auto_now=True)),
                ('delete_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.BookComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.User')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_date', models.DateField(auto_now=True)),
                ('delete_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.User')),
            ],
        ),
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField(null=True)),
                ('delete_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='interestedbook',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='commentfavorite',
            unique_together={('user', 'comment')},
        ),
    ]
