# Generated by Django 2.0.6 on 2019-04-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineers_core_api', '0020_book_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(max_length=10000)),
                ('report_date', models.DateField(null=True)),
                ('tweet_flag', models.BooleanField(default=False)),
                ('delete_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers_core_api.User')),
            ],
        ),
    ]
